[package]
name = "maze"
version = "0.1.0"
authors = ["Jake Kugel <jake_kugel@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
printpdf = "0.3.2"
num-traits = "0.2.14"
